name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  code-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Mill
        uses: zhutmost/setup-mill@main

      - name: Check compilation
        run:
          mill __.compile

      - name: Check formatting
        run:
          mill __.checkFormat

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Verilator
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: verilator
          version: 1.0

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Mill
        uses: zhutmost/setup-mill@main

      - name: Setup Coursier & Firtool
        run: |
          curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > cs
          chmod +x cs
          ./cs launch org.chipsalliance::firtool-resolver:2.0.1 -M firtoolresolver.Main -- 1.62.1

      - name: Run tests
        run:
          mill __.test
