name: Continuous Integration

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check formatting
        run:
          ./mill -i __.checkFormat

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run tests
        run:
          ./mill -i __.test
