name: GitHub Dependency Graph

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  submit-dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Coursier Cache
        uses: coursier/cache-action@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Mill
        uses: zhutmost/setup-mill@main

      - name: Submit Dependency Graph
        uses: ckipp01/mill-dependency-submission@v1
